controller_list:
  - name: fake_Arm_controller
    joints:
      - arm_0_joint
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
  - name: fake_Hand_controller
    joints:
      - arm_5_joint
      - finger_joint_0
      - finger_joint_2
      - finger_joint_4
  - name: fake_All_controller
    joints:
      - arm_0_joint
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - finger_joint_0
      - finger_joint_2
      - finger_joint_4