# Template that can be used to load the moveit_simple_controller_manager
# implementation as a MoveIt! controller for the Jaco arm.
controller_list:
  - name: jaco 
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_0_joint
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - finger_joint_0
      - finger_joint_2
      - finger_joint_4
