# moveit_multidof_controller parameters for the Jaco arm.

# Specify virtual joint name *if* the robot has one.
# Leave unspecified or empty string otherwise.
# virtual_joint_name: ""

# Action topic to subscribe to which provides a
# path_navigation_msgs/PathExecution.action for the robot.
# Required if robot has a virtual joint.
# If virtual_joint_name is empty, this field will be ignored.
path_navigation_action_topic: /navigate_path

# Action topic to subscribe to which provides a
# control_msgs/FollowJointTrajectoryAction action for the robot
joint_trajectory_action_topic: /jaco/joint_trajectory_action

# List of controllers. Specify as for moveit_simple_controller_manager.
controller_list:
  - name: jaco
    type: FollowRobotTrajectory
    default: true
    joints:
      - arm_0_joint
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - finger_joint_0
      - finger_joint_2
      - finger_joint_4
